/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package externaldbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ExternalDBTest service. Represents a row in the &quot;ExternalDB_ExternalDBTest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>externaldbservice.model.impl.ExternalDBTestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>externaldbservice.model.impl.ExternalDBTestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExternalDBTest
 * @generated
 */
@ProviderType
public interface ExternalDBTestModel
	extends BaseModel<ExternalDBTest>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a external db test model instance should use the {@link ExternalDBTest} interface instead.
	 */

	/**
	 * Returns the primary key of this external db test.
	 *
	 * @return the primary key of this external db test
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this external db test.
	 *
	 * @param primaryKey the primary key of this external db test
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this external db test.
	 *
	 * @return the uuid of this external db test
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this external db test.
	 *
	 * @param uuid the uuid of this external db test
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this external db test.
	 *
	 * @return the foo ID of this external db test
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this external db test.
	 *
	 * @param fooId the foo ID of this external db test
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the group ID of this external db test.
	 *
	 * @return the group ID of this external db test
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this external db test.
	 *
	 * @param groupId the group ID of this external db test
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this external db test.
	 *
	 * @return the company ID of this external db test
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this external db test.
	 *
	 * @param companyId the company ID of this external db test
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this external db test.
	 *
	 * @return the user ID of this external db test
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this external db test.
	 *
	 * @param userId the user ID of this external db test
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this external db test.
	 *
	 * @return the user uuid of this external db test
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this external db test.
	 *
	 * @param userUuid the user uuid of this external db test
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this external db test.
	 *
	 * @return the user name of this external db test
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this external db test.
	 *
	 * @param userName the user name of this external db test
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this external db test.
	 *
	 * @return the create date of this external db test
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this external db test.
	 *
	 * @param createDate the create date of this external db test
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this external db test.
	 *
	 * @return the modified date of this external db test
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this external db test.
	 *
	 * @param modifiedDate the modified date of this external db test
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this external db test.
	 *
	 * @return the name of this external db test
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this external db test.
	 *
	 * @param name the name of this external db test
	 */
	public void setName(String name);

	/**
	 * Returns the eid of this external db test.
	 *
	 * @return the eid of this external db test
	 */
	public int getEid();

	/**
	 * Sets the eid of this external db test.
	 *
	 * @param eid the eid of this external db test
	 */
	public void setEid(int eid);

	@Override
	public ExternalDBTest cloneWithOriginalValues();

}