/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package moduleblacklistservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Portlet service. Represents a row in the &quot;ModuleBlaclist_Portlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>moduleblacklistservice.model.impl.PortletModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>moduleblacklistservice.model.impl.PortletImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Portlet
 * @generated
 */
@ProviderType
public interface PortletModel
	extends BaseModel<Portlet>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portlet model instance should use the {@link Portlet} interface instead.
	 */

	/**
	 * Returns the primary key of this portlet.
	 *
	 * @return the primary key of this portlet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this portlet.
	 *
	 * @param primaryKey the primary key of this portlet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this portlet.
	 *
	 * @return the uuid of this portlet
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this portlet.
	 *
	 * @param uuid the uuid of this portlet
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this portlet.
	 *
	 * @return the ID of this portlet
	 */
	public long getId();

	/**
	 * Sets the ID of this portlet.
	 *
	 * @param id the ID of this portlet
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this portlet.
	 *
	 * @return the group ID of this portlet
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this portlet.
	 *
	 * @param groupId the group ID of this portlet
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this portlet.
	 *
	 * @return the company ID of this portlet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this portlet.
	 *
	 * @param companyId the company ID of this portlet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this portlet.
	 *
	 * @return the user ID of this portlet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this portlet.
	 *
	 * @param userId the user ID of this portlet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this portlet.
	 *
	 * @return the user uuid of this portlet
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this portlet.
	 *
	 * @param userUuid the user uuid of this portlet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this portlet.
	 *
	 * @return the user name of this portlet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this portlet.
	 *
	 * @param userName the user name of this portlet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this portlet.
	 *
	 * @return the create date of this portlet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this portlet.
	 *
	 * @param createDate the create date of this portlet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this portlet.
	 *
	 * @return the modified date of this portlet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this portlet.
	 *
	 * @param modifiedDate the modified date of this portlet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the portlet ID of this portlet.
	 *
	 * @return the portlet ID of this portlet
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this portlet.
	 *
	 * @param portletId the portlet ID of this portlet
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the active of this portlet.
	 *
	 * @return the active of this portlet
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this portlet is active.
	 *
	 * @return <code>true</code> if this portlet is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this portlet is active.
	 *
	 * @param active the active of this portlet
	 */
	public void setActive(boolean active);

	@Override
	public Portlet cloneWithOriginalValues();

}