/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapp.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import userapp.model.UserApp;
import userapp.model.UserAppModel;

/**
 * The base model implementation for the UserApp service. Represents a row in the &quot;App_UserApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserAppModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserAppImpl
 * @generated
 */
@JSON(strict = true)
public class UserAppModelImpl
	extends BaseModelImpl<UserApp> implements UserAppModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user app model instance should use the <code>UserApp</code> interface instead.
	 */
	public static final String TABLE_NAME = "App_UserApp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"appId", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"link", Types.VARCHAR},
		{"logoUrl", Types.VARCHAR}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("link", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logoUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table App_UserApp (uuid_ VARCHAR(75) null,appId VARCHAR(75) not null primary key,description VARCHAR(75) null,link VARCHAR(75) null,logoUrl VARCHAR(75) null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table App_UserApp";

	public static final String ORDER_BY_JPQL = " ORDER BY userApp.appId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY App_UserApp.appId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UserAppModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _appId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return UserApp.class;
	}

	@Override
	public String getModelClassName() {
		return UserApp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserApp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((UserApp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserApp, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserApp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserApp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserApp, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserApp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<UserApp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserApp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserApp, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UserApp, Object>>();
		Map<String, BiConsumer<UserApp, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UserApp, ?>>();

		attributeGetterFunctions.put("uuid", UserApp::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<UserApp, String>)UserApp::setUuid);
		attributeGetterFunctions.put("appId", UserApp::getAppId);
		attributeSetterBiConsumers.put(
			"appId", (BiConsumer<UserApp, String>)UserApp::setAppId);
		attributeGetterFunctions.put("description", UserApp::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<UserApp, String>)UserApp::setDescription);
		attributeGetterFunctions.put("link", UserApp::getLink);
		attributeSetterBiConsumers.put(
			"link", (BiConsumer<UserApp, String>)UserApp::setLink);
		attributeGetterFunctions.put("logoUrl", UserApp::getLogoUrl);
		attributeSetterBiConsumers.put(
			"logoUrl", (BiConsumer<UserApp, String>)UserApp::setLogoUrl);
		attributeGetterFunctions.put("name", UserApp::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<UserApp, String>)UserApp::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getAppId() {
		if (_appId == null) {
			return "";
		}
		else {
			return _appId;
		}
	}

	@Override
	public void setAppId(String appId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appId = appId;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getLink() {
		if (_link == null) {
			return "";
		}
		else {
			return _link;
		}
	}

	@Override
	public void setLink(String link) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_link = link;
	}

	@JSON
	@Override
	public String getLogoUrl() {
		if (_logoUrl == null) {
			return "";
		}
		else {
			return _logoUrl;
		}
	}

	@Override
	public void setLogoUrl(String logoUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logoUrl = logoUrl;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public UserApp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserApp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserAppImpl userAppImpl = new UserAppImpl();

		userAppImpl.setUuid(getUuid());
		userAppImpl.setAppId(getAppId());
		userAppImpl.setDescription(getDescription());
		userAppImpl.setLink(getLink());
		userAppImpl.setLogoUrl(getLogoUrl());
		userAppImpl.setName(getName());

		userAppImpl.resetOriginalValues();

		return userAppImpl;
	}

	@Override
	public UserApp cloneWithOriginalValues() {
		UserAppImpl userAppImpl = new UserAppImpl();

		userAppImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		userAppImpl.setAppId(this.<String>getColumnOriginalValue("appId"));
		userAppImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		userAppImpl.setLink(this.<String>getColumnOriginalValue("link"));
		userAppImpl.setLogoUrl(this.<String>getColumnOriginalValue("logoUrl"));
		userAppImpl.setName(this.<String>getColumnOriginalValue("name"));

		return userAppImpl;
	}

	@Override
	public int compareTo(UserApp userApp) {
		String primaryKey = userApp.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserApp)) {
			return false;
		}

		UserApp userApp = (UserApp)object;

		String primaryKey = userApp.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserApp> toCacheModel() {
		UserAppCacheModel userAppCacheModel = new UserAppCacheModel();

		userAppCacheModel.uuid = getUuid();

		String uuid = userAppCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			userAppCacheModel.uuid = null;
		}

		userAppCacheModel.appId = getAppId();

		String appId = userAppCacheModel.appId;

		if ((appId != null) && (appId.length() == 0)) {
			userAppCacheModel.appId = null;
		}

		userAppCacheModel.description = getDescription();

		String description = userAppCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			userAppCacheModel.description = null;
		}

		userAppCacheModel.link = getLink();

		String link = userAppCacheModel.link;

		if ((link != null) && (link.length() == 0)) {
			userAppCacheModel.link = null;
		}

		userAppCacheModel.logoUrl = getLogoUrl();

		String logoUrl = userAppCacheModel.logoUrl;

		if ((logoUrl != null) && (logoUrl.length() == 0)) {
			userAppCacheModel.logoUrl = null;
		}

		userAppCacheModel.name = getName();

		String name = userAppCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			userAppCacheModel.name = null;
		}

		return userAppCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserApp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UserApp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UserApp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UserApp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserApp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((UserApp)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserApp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserApp.class, ModelWrapper.class);

	}

	private String _uuid;
	private String _appId;
	private String _description;
	private String _link;
	private String _logoUrl;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UserApp, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserApp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("appId", _appId);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("link", _link);
		_columnOriginalValues.put("logoUrl", _logoUrl);
		_columnOriginalValues.put("name", _name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("appId", 2L);

		columnBitmasks.put("description", 4L);

		columnBitmasks.put("link", 8L);

		columnBitmasks.put("logoUrl", 16L);

		columnBitmasks.put("name", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserApp _escapedModel;

}